/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useEffect, useState } from 'react';
import partnerAuthService from '../services/partnerAuthService';
import pushNotificationService from '../services/pushNotificationService';
import { getClientDescription } from '../stores/detectDevice';

// ✅ Create context
const PartnerAuthContext = createContext({
  partner: null,
  login: async () => {},
  register: async () => {},
  logout: async () => {},
  updateProfile: async () => {},
  changePassword: async () => {},
  isAuthenticated: false,
  isLoading: true,
  isSubscribedToNotifications: false,
  subscribeToNotifications: async () => {},
  unsubscribeFromNotifications: async () => {},
  unsubscribeAllDevices: async () => {},
  getSubscriptions: async () => [],
});

// ✅ Provider
export const PartnerAuthProvider = ({ children }) => {
  const [partner, setPartner] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubscribedToNotifications, setIsSubscribedToNotifications] = useState(false);

  const updateAuthState = (userData, authStatus) => {
    setPartner(userData);
    setIsAuthenticated(authStatus);
    if (!authStatus) {
      setIsSubscribedToNotifications(false);
    }
  };

  // 🔧 Helper function to convert VAPID key
  const urlBase64ToUint8Array = (base64String) => {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
  };

  // 🔔 Subscribe to push notifications
  const subscribeToNotifications = async (label) => {
    if (!partner?.id) {
      throw new Error('Partner must be logged in to subscribe');
    }

    try {
      // 1. Check if browser supports notifications
      if (!('Notification' in window) || !('serviceWorker' in navigator)) {
        throw new Error('Push notifications not supported in this browser');
      }

      // 2. Request permission
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        throw new Error('Notification permission denied');
      }

      // 3. Wait for service worker to be ready
      const registration = await navigator.serviceWorker.ready;

      // 4. Get VAPID public key from environment
      const publicVapidKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
      if (!publicVapidKey) {
        throw new Error('VAPID public key not configured');
      }

      // 5. Subscribe to push manager
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicVapidKey),
      });

      // 6. Convert subscription to plain object
      const subscriptionObject = subscription.toJSON();
      console.log('Partner subscription:', subscription);

      // 7. Send subscription to backend using push notification service
      await pushNotificationService.subscribe(
        partner.id,
        'PARTNER',
        {
          id: '', // Will be generated by backend
          userId: partner.id,
          type: 'PARTNER',
          endpoint: subscriptionObject.endpoint,
          p256dh: subscriptionObject.keys.p256dh,
          auth: subscriptionObject.keys.auth,
          label: label || `${navigator.userAgent.includes('Mobile') ? 'Mobile' : 'Desktop'} Device`,
          createdAt: new Date().toISOString(),
        },
        label
      );

      setIsSubscribedToNotifications(true);

      console.log('✅ Successfully subscribed to push notifications');
      return { success: true, message: 'Successfully subscribed to notifications' };
    } catch (error) {
      console.error('❌ Error subscribing to notifications:', error);
      throw new Error(error?.message || 'Failed to subscribe to notifications');
    }
  };

  // 🔕 Unsubscribe from push notifications (current device only)
  const unsubscribeFromNotifications = async () => {
    if (!partner?.id) {
      throw new Error('Partner must be logged in');
    }

    try {
      // 1. Unsubscribe from push manager
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        const endpoint = subscription.endpoint;
        
        // Unsubscribe from browser
        await subscription.unsubscribe();

        // 2. Remove subscription from backend
        await pushNotificationService.unsubscribeDevice(
          partner.id,
          'PARTNER',
          endpoint
        );
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed from push notifications');
      return { success: true, message: 'Successfully unsubscribed from notifications' };
    } catch (error) {
      console.error('❌ Error unsubscribing from notifications:', error);
      throw new Error(error?.message || 'Failed to unsubscribe from notifications');
    }
  };

  // 🔕 Unsubscribe all devices
  const unsubscribeAllDevices = async () => {
    if (!partner?.id) {
      throw new Error('Partner must be logged in');
    }

    try {
      // Remove all subscriptions from backend
      await pushNotificationService.unsubscribeAllDevices(
        partner.id,
        'PARTNER'
      );

      // Also unsubscribe current device from browser
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await subscription.unsubscribe();
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed all devices');
      return { success: true, message: 'Successfully unsubscribed all devices' };
    } catch (error) {
      console.error('❌ Error unsubscribing all devices:', error);
      throw new Error(error?.message || 'Failed to unsubscribe all devices');
    }
  };

  // 📋 Get all subscriptions for current partner
  const getSubscriptions = async () => {
    if (!partner?.id) {
      throw new Error('Partner must be logged in');
    }

    try {
      const subscriptions = await pushNotificationService.getSubscriptions(
        partner.id,
        'PARTNER'
      );
      return subscriptions;
    } catch (error) {
      console.error('❌ Error fetching subscriptions:', error);
      throw new Error(error?.message || 'Failed to fetch subscriptions');
    }
  };

  // 🔍 Check if current device is subscribed
  const checkSubscriptionStatus = async () => {
    if (!partner?.id || !isAuthenticated) return;

    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        // Verify with backend
        const subscriptions = await pushNotificationService.getSubscriptions(
          partner.id,
          'PARTNER'
        );
        
        const isSubscribed = subscriptions.some(
          (sub) => sub.endpoint === subscription.endpoint
        );
        
        setIsSubscribedToNotifications(isSubscribed);
      } else {
        setIsSubscribedToNotifications(false);
      }
    } catch (error) {
      console.warn('Could not check subscription status:', error);
      setIsSubscribedToNotifications(false);
    }
  };

  // 🔹 Register
  const register = async (data) => {
    try {
      const response = await partnerAuthService.register(data);
      updateAuthState(null, false);
      return response.partner;
    } catch (error) {
      throw new Error(error?.message || 'Registration failed');
    }
  };

  // 🔹 Login
  const login = async (credentials) => {
    try {
      const response = await partnerAuthService.login(credentials);
      updateAuthState(response.partner, true);
      return response.partner;
    } catch (error) {
      throw new Error(error?.message || 'Login failed');
    }
  };

  // 🔹 Logout
  const logout = async () => {
    try {
      await partnerAuthService.logout();
      updateAuthState(null, false);
    } catch (error) {
      updateAuthState(null, false);
      throw new Error(error?.message || 'Logout failed');
    }
  };

  // 🔹 Update profile
  const updateProfile = async (updates) => {
    try {
      const updatedPartner = await partnerAuthService.editProfile(updates);
      updateAuthState(updatedPartner, true);
      return updatedPartner;
    } catch (error) {
      throw new Error(error?.message || 'Failed to update profile');
    }
  };

  // 🔹 Change password
  const changePassword = async (passwordData) => {
    try {
      return await partnerAuthService.changePassword(passwordData);
    } catch (error) {
      throw new Error(error?.message || 'Failed to change password');
    }
  };

  // 🔹 Check existing session (auto-login)
  const checkAuthStatus = async () => {
    setIsLoading(true);
    try {
      const profile = await partnerAuthService.getProfile();
      if (profile) {
        updateAuthState(profile, true);
      } else {
        updateAuthState(null, false);
      }
    } catch {
      updateAuthState(null, false);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    checkAuthStatus();
  }, []);

  // 🔍 Check subscription status when authenticated
  useEffect(() => {
    if (isAuthenticated && !isLoading && partner?.id) {
      checkSubscriptionStatus();
    }
  }, [isAuthenticated, isLoading, partner?.id]);

  // 🔔 Auto-subscribe on login (optional)
  useEffect(() => {
    const autoSubscribe = async () => {
      // Only run if authenticated and not already subscribed
      if (!isAuthenticated || isLoading || !partner?.id || isSubscribedToNotifications) {
        return;
      }

      // Check if partner wants auto-subscribe
      const autoSubscribeEnabled = true;
      const client = getClientDescription();
      
      if (autoSubscribeEnabled) {
        try {
          await subscribeToNotifications(client.description || 'Auto-subscribed device');
        } catch (error) {
          console.warn('Auto-subscribe failed:', error);
        }
      }
    };

    autoSubscribe();
  }, [isAuthenticated, isLoading, partner?.id, isSubscribedToNotifications]);

  const value = {
    partner,
    login,
    register,
    logout,
    updateProfile,
    changePassword,
    subscribeToNotifications,
    unsubscribeFromNotifications,
    unsubscribeAllDevices,
    getSubscriptions,
    isAuthenticated,
    isLoading,
    isSubscribedToNotifications,
  };

  return (
    <PartnerAuthContext.Provider value={value}>
      {children}
    </PartnerAuthContext.Provider>
  );
};

// ✅ Hook
export const usePartnerAuth = () => {
  const context = useContext(PartnerAuthContext);
  if (!context) {
    throw new Error('usePartnerAuth must be used within a PartnerAuthProvider');
  }
  return context;
};