-- AlterTable
ALTER TABLE `employee` ADD COLUMN `cv` VARCHAR(191) NULL,
    ADD COLUMN `identityCard` VARCHAR(191) NULL,
    ADD COLUMN `password` VARCHAR(191) NULL,
    ADD COLUMN `profileImg` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE';
